class Credentials:
    """Base GCP credential from ADC — identity: APP."""
    ...

class AnonymousCredentials(Credentials): ...
class Scoped(Credentials): ...
class ReadOnlyScoped(Credentials): ...
class Signing(Credentials): ...
